import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  containerContent: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    // justifyContent: 'space-between',
    // top: 50,
    // marginBottom: 300,
    backgroundColor: 'white',
  },
  authors: {
    flex: 0.15,
    width: '85%',
    top: 30,
    marginBottom: 30,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    borderRadius: 20,
    backgroundColor: '#1B1F3B',
  },
  authorsTitleFocused: {
    flex: 0.15,
    width: '85%',
    top: 30,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: '#1B1F3B',
  },
  authorsFocused: {
    flex: 0.8,
    overflow: 'scroll',
    marginTop: 25,
    width: '85%',
    alignItems: 'stretch',
    justifyContent: 'space-evenly',
    borderBottomLeftRadius: 21,
    borderBottomRightRadius: 21,
    borderColor: '#1B1F3B',
    borderWidth: 2,
    backgroundColor: '#1B1F3B',
  },
  authorsButton: {
    fontFamily: 'Roboto_500Medium',
    fontWeight: 'bold',
    fontSize: 23,
    color: 'white',
  },
  authorsInfoTitleMain: {
    fontFamily: 'Roboto_500Medium',
    fontWeight: 'bold',
    fontSize: 23,
    paddingLeft: 30,
    paddingBottom: 15,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    color: 'white',
    backgroundColor: '#1B1F3B',
  },
  authorsInfoTitle: {
    fontFamily: 'Roboto_500Medium',
    fontWeight: 'bold',
    paddingLeft: 30,
    paddingTop: 15,
    paddingBottom: 15,
    fontSize: 23,
    color: 'white',
    backgroundColor: '#1B1F3B',
  },
  authorsInfoName: {
    paddingLeft: 30,
    marginTop: 2,
    marginBottom: -5,
    fontFamily: 'Roboto_500Medium',
    fontSize: 17,
    fontWeight: 'bold',
    color: 'white',
  },
  authorsInfoUsp: {
    paddingLeft: 30,
    fontFamily: 'Roboto_500Medium',
    fontSize: 15,
    color: 'white',
    opacity: 0.5,
    marginBottom: 10,
  }
});

export default styles;